#!/usr/bin/env bun
/**
 * Build-time script that embeds the llm-wiki-for-backlog skill files
 * into a TypeScript module so they are available in the compiled binary.
 */
import { readdir, readFile } from "node:fs/promises";
import { join, relative } from "node:path";

const SKILL_DIR = join(import.meta.dir, "..", ".codex", "skills", "llm-wiki-for-backlog");
const OUTPUT_FILE = join(import.meta.dir, "..", "src", "skills", "embedded", "llm-wiki-for-backlog.ts");

async function collectFiles(dir: string, baseDir: string): Promise<Record<string, string>> {
	const result: Record<string, string> = {};
	const entries = await readdir(dir, { withFileTypes: true });

	for (const entry of entries) {
		const fullPath = join(dir, entry.name);
		const relPath = relative(baseDir, fullPath).replace(/\\/g, "/");

		if (entry.isDirectory()) {
			const nested = await collectFiles(fullPath, baseDir);
			Object.assign(result, nested);
		} else {
			const content = await readFile(fullPath, "utf-8");
			result[relPath] = content;
		}
	}

	return result;
}

async function main(): Promise<void> {
	const files = await collectFiles(SKILL_DIR, SKILL_DIR);

	const entries = Object.entries(files)
		.map(([path, content]) => {
			const escaped = content
				.replace(/\\/g, "\\\\")
				.replace(/`/g, "\\`")
				.replace(/\${/g, "\\${");
			return `\t"${path}": \`${escaped}\`,`;
		})
		.join("\n");

	const output = `// AUTO-GENERATED by scripts/embed-wiki-skill.ts
// Do not edit manually. Run the script to regenerate.

export const LLM_WIKI_FOR_BACKLOG_SKILL: Record<string, string> = {
${entries}
};
`;

	await Bun.write(OUTPUT_FILE, output);
	console.log(`Embedded ${Object.keys(files).length} files from llm-wiki-for-backlog skill into ${OUTPUT_FILE}`);
}

main().catch((err) => {
	console.error("Failed to embed wiki skill:", err);
	process.exit(1);
});
